=== zmokiem-ui/MDES-XML-Studio/electron-app/XSD/7500 XSD/CBC Status Message/Versie 2.0/CbcStatusMessageXML_v2.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2012 rel. 2 sp1 (x64) (http://www.altova.com) by Sebastien Michon (OECD) -->
<xsd:schema xmlns:stm="urn:oecd:ties:cbcstm:v2" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:iso="urn:oecd:ties:cbcstm:isostmtypes:v1" targetNamespace="urn:oecd:ties:cbcstm:v2" elementFormDefault="qualified" attributeFormDefault="unqualified" version="2.0">
	<xsd:import namespace="urn:oecd:ties:cbcstm:isostmtypes:v1" schemaLocation="isostmtypes_v1.1.xsd"/>
	<!-- -->
	<!--+++++++++++++++++++++++  String lenght types ++++++++++++++++++++++++++++++++++++++ -->
	<!-- -->
	<!-- Defines a string with minimum length 1 and maximum length of 10 -->
	<xsd:simpleType name="StringMin1Max10_Type">
		<xsd:annotation>
			<xsd:documentation>Defines a string with minimum length 1 and maximum length of 10</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1"/>
			<xsd:maxLength value="10"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- -->
	<!-- Defines a string with minimum length 1 and maximum length of 170 -->
	<xsd:simpleType name="StringMin1Max170_Type">
		<xsd:annotation>
			<xsd:documentation>Defines a string with minimum length 1 and maximum length of 170</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1"/>
			<xsd:maxLength value="170"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- -->
	<!-- Defines a string with minimum length 1 and maximum length of 200 -->
	<xsd:simpleType name="StringMin1Max200_Type">
		<xsd:annotation>
			<xsd:documentation>Defines a string with minimum length 1 and maximum length of 200</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1"/>
			<xsd:maxLength value="200"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- -->
	<!-- Defines a string with minimum length 1 and maximum length of 400 -->
	<xsd:simpleType name="StringMin1Max400_Type">
		<xsd:annotation>
			<xsd:documentation>Defines a string with minimum length 1 and maximum length of 400</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1"/>
			<xsd:maxLength value="400"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- -->
	<!-- Defines a string with minimum length 1 and maximum length of 4000 -->
	<xsd:simpleType name="StringMin1Max4000_Type">
		<xsd:annotation>
			<xsd:documentation>Defines a string with minimum length 1 and maximum length of 4000</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1"/>
			<xsd:maxLength value="4000"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- -->
	<!--+++++++++++++++++++++++  Reusable Simple types ++++++++++++++++++++++++++++++++++++++ -->
	<!-- Message type definitions -->
	<xsd:simpleType name="MessageType_EnumType">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">Message type defines the type of reporting</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="CbCMessageStatus"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!--  -->
	<!-- MessageTypeIndic -->
	<xsd:simpleType name="CbCMessageTypeIndic_EnumType">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">The MessageTypeIndic is currently not used for CbC Status message (for future use)</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="CbCMessageStatus"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!--  -->
	<!-- FileAcceptanceStatus -->
	<xsd:simpleType name="FileAcceptanceStatus_EnumType">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">File acceptance status: if the file was accepted or rejected by the receiver</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Accepted">
				<xsd:annotation>
					<xsd:documentation>The file was accepted by the receiver</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="Rejected">
				<xsd:annotation>
					<xsd:documentation>The file was rejected by the receiver</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<!--  -->
	<!--++++++++++++++++++ Reusable Complex types +++++++++++++++++++++++++++++++++++++ -->
	<!-- Message specification: Data identifying and describing the message as a whole -->
	<xsd:complexType name="MessageSpec_Type">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">Information in the message header identifies the Tax Administration that is sending the message.  It specifies when the message was created, what period (normally a year) the report is for, and the nature of the report (original, corrected, supplemental, etc).</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="SendingCompanyIN" type="stm:StringMin1Max200_Type" minOccurs="0"/>
			<xsd:element name="TransmittingCountry" type="iso:CountryCode_Type"/>
			<xsd:element name="ReceivingCountry" type="iso:CountryCode_Type"/>
			<xsd:element name="MessageType" type="stm:MessageType_EnumType"/>
			<xsd:element name="Warning" type="stm:StringMin1Max4000_Type" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation xml:lang="en">Free text expressing the restrictions for use of the information this
message contains and the legal framework under which it is given</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Contact" type="stm:StringMin1Max4000_Type" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation xml:lang="en">All necessary contact information about persons responsible for and
involved in the processing of the data transmitted in this message, both legally and technically. Free text as this is not
intended for automatic processing. </xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="MessageRefId" type="stm:StringMin1Max170_Type">
				<xsd:annotation>
					<xsd:documentation xml:lang="en">Unique identifier for this CbC Status message</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="MessageTypeIndic" type="stm:CbCMessageTypeIndic_EnumType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Not used for CbC Status message</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="CorrMessageRefId" type="stm:StringMin1Max170_Type" minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>Not used for CbC Status message</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="ReportingPeriod" type="xsd:date" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Not used for CbC Status message</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Timestamp" type="xsd:dateTime"/>
		</xsd:sequence>
	</xsd:complexType>
	<!-- -->
	<!-- Record Error type   -->
	<xsd:complexType name="RecordError_Type">
		<xsd:sequence>
			<xsd:element name="Code" type="stm:StringMin1Max10_Type">
				<xsd:annotation>
					<xsd:documentation xml:lang="en">Error Code</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Details" type="stm:ErrorDetail_Type" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation xml:lang="en">Error Details</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="DocRefIDInError" type="stm:StringMin1Max200_Type" minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation xml:lang="en">DocRefID of the record causing the error</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="FieldsInError" minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation xml:lang="en">Information on the fields causing the error</xsd:documentation>
				</xsd:annotation>
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="FieldPath" type="stm:StringMin1Max400_Type"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<!-- -->
	<!-- File Error type   -->
	<xsd:complexType name="FileError_Type">
		<xsd:sequence>
			<xsd:element name="Code" type="stm:StringMin1Max10_Type">
				<xsd:annotation>
					<xsd:documentation xml:lang="en">Error Code</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Details" type="stm:ErrorDetail_Type" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation xml:lang="en">Error Details</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<!-- -->
	<!-- Error Detail Type -->
	<xsd:complexType name="ErrorDetail_Type">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">Error message provide more details about the error</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleContent>
			<xsd:extension base="stm:StringMin1Max4000_Type">
				<xsd:attribute name="Language" type="iso:LanguageCode_Type"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<!--  -->
	<!-- File Meta Data type   -->
	<xsd:complexType name="FileMetaData_Type">
		<xsd:sequence>
			<xsd:element name="CTSTransmissionID" type="stm:StringMin1Max200_Type" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation xml:lang="en">CTS Transmission ID assigned to the original transmission by CTS when it was initially received</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="CTSSendingTimeStamp" type="xsd:dateTime" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation xml:lang="en">The date and time the original transmission was initially delivered to the Receiver by CTS</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="UncompressedFileSizeKBQty" type="xsd:integer" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation xml:lang="en">Uncompressed File size (KB)</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<!-- -->
	<!-- Original Message Type -->
	<xsd:complexType name="OriginalMessage_Type">
		<xsd:sequence>
			<xsd:element name="OriginalMessageRefID" type="stm:StringMin1Max170_Type" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation xml:lang="en">The MessageRefID of the original CbC message for which the Status Message is provided</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="FileMetaData" type="stm:FileMetaData_Type" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<!-- -->
	<!-- Validation Errors Type -->
	<xsd:complexType name="ValidationErrors_Type">
		<xsd:sequence>
			<xsd:element name="FileError" type="stm:FileError_Type" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="RecordError" type="stm:RecordError_Type" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<!-- -->
	<!-- Validation Result Type -->
	<xsd:complexType name="ValidationResult_Type">
		<xsd:sequence>
			<xsd:element name="Status" type="stm:FileAcceptanceStatus_EnumType">
				<xsd:annotation>
					<xsd:documentation xml:lang="en">Indicate if the file was accepted or rejected by the receiver</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="ValidatedBy" type="stm:StringMin1Max400_Type" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation xml:lang="en">Indicate the version of the validation tool that was used to generate this Status Message</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<!-- -->
	<!-- CbC Status Message Type -->
	<xsd:complexType name="CbCMessageStatus_Type">
		<xsd:sequence>
			<xsd:element name="OriginalMessage" type="stm:OriginalMessage_Type"/>
			<xsd:element name="ValidationErrors" type="stm:ValidationErrors_Type"/>
			<xsd:element name="ValidationResult" type="stm:ValidationResult_Type"/>
		</xsd:sequence>
	</xsd:complexType>
	<!-- -->
	<!--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++ Schema  element ++++++++++++++++++++++++++++++++++++++++++++ -->
	<!-- -->
	<!-- CbC Status Message structure  -->
	<xsd:element name="CbCStatusMessage_OECD">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="MessageSpec" type="stm:MessageSpec_Type"/>
				<xsd:element name="CbCStatusMessage" type="stm:CbCMessageStatus_Type"/>
			</xsd:sequence>
			<xsd:attribute name="version" type="stm:StringMin1Max10_Type" fixed="2.0">
				<xsd:annotation>
					<xsd:documentation xml:lang="en">CbC Status Message Version</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	<!-- -->
</xsd:schema>

=== zmokiem-ui/MDES-XML-Studio/crs_generator/template CBC/CBCSM.Generiek.2019.Valid.xml
<?xml version="1.0" encoding="UTF-8"?>
<cbcstm:CbCStatusMessage_OECD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
						   xmlns:cbcstm="urn:oecd:ties:cbcstm:v2"
               xmlns:isostm="urn:oecd:ties:cbcstm:isostmtypes:v1"
						   xsi:schemaLocation="urn:oecd:ties:csm:v1 CbcStatusMessageXML_v2.0.xsd" version="2.0">
  <cbcstm:MessageSpec>
    <cbcstm:TransmittingCountry>SENDINGCOUNTRY</cbcstm:TransmittingCountry>
    <cbcstm:ReceivingCountry>RECEIVINGCOUNTRY</cbcstm:ReceivingCountry>
    <cbcstm:MessageType>CbCMessageStatus</cbcstm:MessageType>
    <cbcstm:Warning>Warning about CBC</cbcstm:Warning>
    <cbcstm:Contact>Contact John</cbcstm:Contact>
    <cbcstm:MessageRefId>StatusSENDINGCOUNTRY2019RECEIVINGCOUNTRYRANDOMID</cbcstm:MessageRefId>    
    <cbcstm:ReportingPeriod>2019-12-31</cbcstm:ReportingPeriod>
    <cbcstm:Timestamp>2019-04-21T15:55:54.434910Z</cbcstm:Timestamp>
  </cbcstm:MessageSpec>
  <cbcstm:CbCStatusMessage>
    <cbcstm:OriginalMessage>
      <cbcstm:OriginalMessageRefID>RECEIVINGCOUNTRY2019-RANDOMNUMBER</cbcstm:OriginalMessageRefID>
      <cbcstm:FileMetaData>
        <cbcstm:CTSTransmissionID>12348901245678901234567890-12345</cbcstm:CTSTransmissionID>
        <cbcstm:CTSSendingTimeStamp>2019-01-01T12:00:00.000Z</cbcstm:CTSSendingTimeStamp>
      </cbcstm:FileMetaData>      
    </cbcstm:OriginalMessage>
    <!--<cbcstm:ValidationErrors>
      <cbcstm:FileError>
        <cbcstm:Code></cbcstm:Code>
        <cbcstm:Details></cbcstm:Details>
      </cbcstm:FileError>
      <cbcstm:RecordError>
        <cbcstm:Code></cbcstm:Code>
        <cbcstm:Details></cbcstm:Details>
        <cbcstm:DocRefIDInError></cbcstm:DocRefIDInError>
        <cbcstm:FieldsInError>
          <cbcstm:FieldPath></cbcstm:FieldPath>          
        </cbcstm:FieldsInError>
      </cbcstm:RecordError>
    </cbcstm:ValidationErrors>-->
    <cbcstm:ValidationErrors/>
    <cbcstm:ValidationResult>
      <cbcstm:Status>Accepted</cbcstm:Status>
      <cbcstm:ValidatedBy>MDES 3.0</cbcstm:ValidatedBy>
    </cbcstm:ValidationResult>
  </cbcstm:CbCStatusMessage>
</cbcstm:CbCStatusMessage_OECD>
